// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Launch', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Launch', async function() {
    await driver.get("https://dou.ua/")
    await driver.manage().window().setRect(1440, 818)
    await driver.findElement(By.css(".b-head li:nth-child(3) > a")).click()
    await driver.findElement(By.id("txtGlobalSearch")).click()
    await driver.findElement(By.id("txtGlobalSearch")).sendKeys("selenium")
    await driver.findElement(By.id("txtGlobalSearch")).sendKeys(Key.ENTER)
    {
      const elements = await driver.findElements(By.id("gsc-i-id1"))
      assert(elements.length)
    }
  })
})
